--- 
abstract: The downloads required to build Vanilla Perl distros
author: Adam Kennedy <adamk@cpan.org>
build_requires: 
  ExtUtils::MakeMaker: 6.11
distribution_type: module
generated_by: Module::Install version 0.65
license: perl
meta-spec: 
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: Perl-Dist-Downloads
no_index: 
  directory: 
    - inc
    - t
requires: 
  File::ShareDir: 0.05
  perl: 5.005
version: 0.02
